# Generated by Django 5.0.1 on 2024-02-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'member'), ('moderator', 'moderator')], default='member', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличный'), ('transfer', 'Перевод на счет')], default='transfer', max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
