# Generated by Django 5.0.1 on 2024-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Перевод на счет'), ('cash', 'Наличный')], default='transfer', max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
