# Generated by Django 5.0.1 on 2024-02-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличный'), ('transfer', 'Перевод на счет')], default='transfer', max_length=8, verbose_name='Способ оплаты'),
        ),
    ]
